;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        evil-append
        evil-append-line
        evil-backward-char
        evil-backward-paragraph
        evil-backward-word-begin
        evil-change
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-downcase
        evil-end-of-line
        evil-escape-insert-state
        evil-first-non-blank
        evil-force-normal-state
        evil-forward-char
        evil-forward-paragraph
        evil-forward-word-begin
        evil-forward-word-end
        evil-goto-line
        evil-insert
        evil-insert-line
        evil-jump-item
        evil-next-line
        evil-normal-state
        evil-paste-after
        evil-previous-line
        evil-search-next
        evil-snipe-f
        evil-visual-char
        evil-visual-line
        evil-yank
        ))

(setq mc/cmds-to-run-once
      '(
        ))
